pipelines:
  - name: pipeline_hello_world
    steps:
      - name: step_1
        type: Bash
        execution:
          onStart:
            - echo "this is onStart"
          onExecute:
            - echo "execute"
          onSuccess:
            - echo "this is onSuccess"
          onComplete:
            - echo "this is onComplete"
          onFailure:
            - echo "this is onFailure"
            
      - name: step_2
        type: Bash
        configuration:
         inputSteps:
           - name: step_1
        execution:
         onExecute:
           - add_run_variables first_stepid=$step_id
           #- add_run_variables ${first_stepid}_buildNumber=${run_number}

      - name: step_3
        type: Bash
        configuration:
         inputSteps:
           - name: step_2
        execution:
         onExecute:
           - echo "Hello world"
           - echo $first_stepid
           #- echo ${first_stepid}_buildNumber
