pipelines:
  - name: pipeline_hello_world
    steps:
      - name: step_1
        type: Bash
        configuration:
          integrations:
            - name: artifactory
        execution:
          onStart:
            - echo "this is onStart"
          onExecute:
            - printenv
            - cat /var/opt/jfrog/pipelines/pipelines/pipeline_hello_world/runs/11/steps/step_1/11/stepletScript.sh
            - touch foo
            - jfrog rt u foo example-repo-local/foo
            - jfrog rt del example-repo-local/foo
          onSuccess:
            - echo "this is onSuccess"
          onComplete:
            - asd
          onFailure:
            - echo "this is onFailure"
