pipelines:
  - name: pipeline_hello_world
    steps:
      - name: step_1
        type: Bash
        configuration:
          integrations:
            - name: docker
        execution:
          onStart:
            - echo "this is onStart"
          onExecute:
            - printenv
          onSuccess:
            - echo "this is onSuccess"
          onComplete:
            - asd
          onFailure:
            - echo "this is onFailure"
