pipelines:
  - name: pipeline_hello_world
    steps:
      - name: step_1
        type: Bash
        configuration:
          integrations:
            - name: artifactory
        execution:
          onStart:
            - echo "this is onStart"
          onExecute:
            - touch foo
            - sleep 5m
            - jfrog rt u foo example-repo-local/foo
            - jfrog rt del example-repo-local/foo
          onSuccess:
            - echo "this is onSuccess"
          onComplete:
            - echo "this is onComplete"
            - asd
            - echo "done"
          onFailure:
            - echo "this is onFailure"
