pipelines:
  - name: pipeline_hello_world
    steps:
      - name: step_1
        type: Bash
        execution:
          onStart:
            - echo "this is onStart"
          onExecute:
            - echo $PATH
            - printenv
          onSuccess:
            - asd
          onComplete:
            - echo "this is onComplete"
